version: '2'

services:
  rabbitmq:
    image: rabbitmq:management-alpine
    expose:
      - '5672'
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: 'zoe'
      RABBITMQ_DEFAULT_PASS: 'zoe'

  zoe-agent-mail:
    build: ./zoe-agent-mail
    depends_on:
      - rabbitmq
    volumes:
      - './zoe-agent-mail/src:/code/src'
    command: 'monitor /code python3 -u /code/src/agent.py'
    environment:
      RABBITMQ_URL: "amqp://zoe:zoe@rabbitmq:5672/%2F"

  zoe-agent-msglog:
    build: ./zoe-agent-msglog
    depends_on:
      - rabbitmq
    volumes:
      - './zoe-agent-msglog/src:/code/src'
    command: 'monitor /code python3 -u /code/src/agent.py'
    environment:
      RABBITMQ_URL: "amqp://zoe:zoe@rabbitmq:5672/%2F"

  zoe-agent-shell:
    build: ./zoe-agent-shell
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: "amqp://zoe:zoe@rabbitmq:5672/%2F"

  zoe-agent-user:
    build: ./zoe-agent-user
    depends_on:
      - rabbitmq
    volumes:
      - './zoe-agent-user/src:/code/src'
    command: 'monitor /code python3 -u /code/src/agent.py'
    environment:
      RABBITMQ_URL: "amqp://zoe:zoe@rabbitmq:5672/%2F"
