version: '3'

services:
  zookeeper:
    image: zookeeper:latest
    restart: always
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka
    restart: always
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_CREATE_TOPICS: zoe:10:1
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  zoe-agent-mail:
    build: ./zoe-agent-mail
    depends_on:
      - kafka
    volumes:
      - './zoe-agent-mail/src:/code/src'
    command: 'monitor /code python3 -u /code/src/agent.py'
    environment:
      KAFKA_SERVERS: kafka:9092

  zoe-agent-msglog:
    build: ./zoe-agent-msglog
    depends_on:
      - kafka
    volumes:
      - './zoe-agent-msglog/src:/code/src'
    command: 'monitor /code python3 -u /code/src/agent.py'
    environment:
      KAFKA_SERVERS: kafka:9092

  zoe-agent-shell:
    build: ./zoe-agent-shell
    volumes:
      - './zoe-agent-shell/src:/code/src'
    environment:
      KAFKA_SERVERS: kafka:9092

  zoe-agent-user:
    build: ./zoe-agent-user
    depends_on:
      - kafka
    volumes:
      - './zoe-agent-user/src:/code/src'
    command: 'monitor /code python3 -u /code/src/agent.py'
    environment:
      KAFKA_SERVERS: kafka:9092
